// ── Server-side tutor orchestrator — DISABLED ────────────────────────────────
// All tutor text generation must use on-device Gemma. The server does NOT run
// any cloud LLM. This function throws to prevent accidental use.

export async function runTutorSession() {
  throw new Error(
    'Server-side tutor generation is disabled. ' +
    'All AI responses must be generated by on-device Gemma. ' +
    'No cloud LLM is permitted.'
  )
}
