// ── tutor-session endpoint — DISABLED ─────────────────────────────────────────
// All tutor text generation must use on-device Gemma. No cloud LLM permitted.

export async function handler(event) {
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
      body: JSON.stringify({ error: 'Method not allowed.' }),
    }
  }
  return {
    statusCode: 410,
    headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
    body: JSON.stringify({
      error: 'Cloud tutor generation is disabled. All AI responses must be generated by on-device Gemma.',
    }),
  }
}
